### ISSUE TITLE
Is it possible to combine R & Python documentation?

### ISSUE THREAD

**Issue by zmeers** [ropenscilabs/r2readthedocs#13]
Hi 👋🏻 ! 
Awesome package - I'm really looking forward to trying it out.
 
I'm currently working on a  package / module in both Python and R. I'd love to be able to combine documentation for both packages into one site. Is this possible with `r2readthedocs`? I have yet to look too deeply into it, but I imagine it would have to involve some manual moving of files from one docs folder to the other in some sort of amalgamation...?
If there is anything in the works surrounding combining multi-language docs, please let me know!

**Comment by mpadge** [comment]
Thanks @zmeers. That's a great idea, and one which actually wouldn't be too hard to do at all. There are plans in the meantime to merge this package with [the altdoc package](https://github.com/etiennebacher/altdoc) by @etiennebacher, but expansion of capabilities here to become a multi-language doc generator might be a good argument for keeping the functionality of this package separate. Any thoughts on this @etiennebacher?

@zmeers Do you have a link to your package/module? I've know of a couple of other dual python/R repos, but would happily use yours as a test case if you could provide a link.

**Comment by etiennebacher** [comment]
Hello @mpadge and @zmeers, I suppose it would be useful to have a multiple language doc generator. Personally, I mostly use R and I never had this need in particular so I don't know how difficult it is to do something like this. Also, I never used Python so I have no idea of the existing tools or the way python docs work.

@mpadge If you are more familiar with this, I suppose it would be useful to keep this in a separate package, simply because I know I will not work on this soon (I already need to finish https://github.com/etiennebacher/altdoc/issues/21 and to think about how to implement sphinx in altdoc). Or if you prefer you can also make a PR to add this in altdoc, I have no problem with this

**Comment by zmeers** [comment]
Unfortunately it's an internal package for work, so I can't share. But I know Prophet has both R and Python packages/modules, as an example.

**Comment by zmeers** [comment]
In particular, what I'd love to have is two reference pages (or a reference page with the ability to switch between Python and R). This is because my python module has classes that don't exist in R and vice versa.

**Comment by mpadge** [comment]
Thanks @zmeers, and no worries about internal. I'll use a couple of others instead, and report back here when things get that far.

**Comment by zmeers** [comment]
I've built something similar, so I'll close this for now (still very much a WIP though and I'm also keen to see if the readthedocs python & R work goes anywhere): https://github.com/zmeers/pyrdocs
